name: jepa-real-time-lsf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pyyaml
  - pytorch
  - matplotlib
  - tqdm
  - pytest
  - pip
  - pip:
      - opencv-python
      - mediapipe
      - sentencepiece

